// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Accordion: typeof import('./src/components/Accordion.vue')['default']
    Button: typeof import('./src/components/Button.vue')['default']
    ClassHighlight: typeof import('./src/components/ClassHighlight.vue')['default']
    ClassIcon: typeof import('./src/components/ClassIcon.vue')['default']
    Filter: typeof import('./src/components/Filter.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    Nav: typeof import('./src/components/Nav.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}

export {}
